name: Auto Comment on PR Merged

on:
  pull_request_target:
    types: [closed] 

permissions:
  issues: write
  pull-requests: write

jobs:
  comment:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Add Comment to Merged Pull Request
        uses: actions/github-script@v6
        with:
          script: |
            const prNumber = context.issue.number;
            const commentBody = `🎉 Congratulations on merging your PR! 🎉\n Thanks for your efforts and contributions! 🙌
            Looking forward to your next contribution! 🚀`;
            try {
              await github.rest.issues.createComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: prNumber,
                body: commentBody
              });
              console.log('Successfully added comment to merged PR.');
            } catch (error) {
              console.error('Failed to add comment to merged PR:', error);
              core.setFailed(`Failed to add comment: ${error.message}`);
            }